### ISSUE TITLE
Connection limitation for 1 ip

### ISSUE THREAD

**Issue by TopoR1** [Yuu6883/OgarX#11]
Due to the fact that there are no connection restrictions for 1 ip, I was able to fill the server with bots. 

Script for tampermonkey: https://github.com/TopoR1/bots/blob/main/bots.js
![image](https://user-images.githubusercontent.com/19995663/111117334-70cd3b00-8578-11eb-9edd-e10b439ac650.png)

**Comment by Yuu6883** [comment]
It was intentional for the stress test I performed for the video here https://www.youtube.com/watch?v=CA--IeniR9Q. IP limiting should be done in the kernel anyways with iptables or some other tools.
