### ISSUE TITLE
Node.js support version

### ISSUE THREAD

**Issue by LaiYueTing** [Yuu6883/OgarX#18]
Excuse me, which version of Node.js will be more stable for Local Development?

**Comment by Yuu6883** [comment]
I did all the development in Node 14 LTS environment, but any recent official release that's compatible with uwebsocket.js should work.

**Comment by LaiYueTing** [comment]
@Yuu6883 
These errors will occur when using npm i ...
https://pastebin.com/pW4zgjNn

**Comment by Yuu6883** [comment]
No idea what going on there. Probably something wrong with your npm.

**Comment by LaiYueTing** [comment]
I use Node.js version number is 14.17.5 LTS

**Comment by Yuu6883** [comment]
This is not an issue with this repo. Some googling tells me if you just delete node_modules and package-lock.json, `npm i` will work.
