### ISSUE TITLE
Client not working

### ISSUE THREAD

**Issue by Faris90** [Yuu6883/OgarX#20]
When I select a server nothing happens must be because of these errors
![image](https://user-images.githubusercontent.com/24720470/131186524-f448256a-f5a6-4f43-887f-0a8927ba79c9.png)
![image](https://user-images.githubusercontent.com/24720470/131187204-27ff7582-3eb5-418c-a4f2-3a74fdc6a407.png)

**Comment by Yuu6883** [comment]
#16
