### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by TopoR1** [Yuu6883/OgarX#9]
Hey! I tried to run your project on Windows and Linux and it does not start anywhere. I read all the documentation - I could not find an answer. I'm waiting for your help!
![image](https://user-images.githubusercontent.com/19995663/110817563-7cc9ac00-829d-11eb-8382-4169af5a0a15.png)
![image](https://user-images.githubusercontent.com/19995663/110817865-c7e3bf00-829d-11eb-9d22-d1247747923c.png)

**Comment by Yuu6883** [comment]
Sorry for not including more setup instructions since I'm assuming people are more familiar with pm2. Try `pm2 log` to see what went wrong in the process.

**Comment by TopoR1** [comment]
@Yuu6883 
![image](https://user-images.githubusercontent.com/19995663/110906080-847c6580-831c-11eb-909c-5ad82ed3f29c.png)

**Comment by Yuu6883** [comment]
Seems like your windows version is some special build or something that uWebSocket is not built with.

**Comment by TopoR1** [comment]
@Yuu6883 On Linux, the same error -_-
![image](https://user-images.githubusercontent.com/19995663/110976622-2b3f2100-8372-11eb-8b88-2fa4dafc1445.png)

**Comment by Yuu6883** [comment]
My bad, I didn't see ur node is too old. Update ur node to latest LTS.

**Comment by TopoR1** [comment]
@Yuu6883 Did not help
![image](https://user-images.githubusercontent.com/19995663/110981314-09489d00-8378-11eb-914e-0a59829ade86.png)

**Comment by Yuu6883** [comment]
Also looks like your pm2 is installed globally under the old version of nodejs which could cause the program to start in an older version of node instead of what `nvm current` outputs
